// FWClib/properties/client/GeneralSearch123_generalPurposeSearch_Screen.properties

export default {
  // ##チャネル検索用画面設定###
  // 検索画面ヘッダ部の表示文字列設定
  'GeneralSearch123.title': 'チャネル検索',

  // 検索条件部項目設定
  'GeneralSearch123.condition.1.labelValue': 'ﾁｬﾈﾙｺｰﾄﾞ',
  'GeneralSearch123.condition.1.fieldType': '1',
  'GeneralSearch123.condition.1.paramName': 'condition01',
  'GeneralSearch123.condition.1.fieldMaxLength': '3',

  'GeneralSearch123.condition.2.labelValue': 'ﾁｬﾈﾙ名称',
  'GeneralSearch123.condition.2.fieldType': '1',
  'GeneralSearch123.condition.2.paramName': 'condition02',
  'GeneralSearch123.condition.2.fieldMaxLength': '50',
  'GeneralSearch123.condition.2.imeFlg': 'true',

  'GeneralSearch123.condition.3.labelValue': '取引形態',
  'GeneralSearch123.condition.3.fieldType': '3',
  'GeneralSearch123.condition.3.paramName': 'condition03',
  'GeneralSearch123.condition.3.fieldMaxLength': '1',
  'GeneralSearch123.condition.3.combo.text.1': 'A',
  'GeneralSearch123.condition.3.combo.id.1': 'A',
  'GeneralSearch123.condition.3.combo.text.2': 'D',
  'GeneralSearch123.condition.3.combo.id.2': 'D',
  'GeneralSearch123.condition.3.combo.text.3': 'E',
  'GeneralSearch123.condition.3.combo.id.3': 'E',
  'GeneralSearch123.condition.3.combo.text.4': 'H',
  'GeneralSearch123.condition.3.combo.id.4': 'H',
  'GeneralSearch123.condition.3.combo.text.5': 'J',
  'GeneralSearch123.condition.3.combo.id.5': 'J',
  'GeneralSearch123.condition.3.combo.text.6': 'M',
  'GeneralSearch123.condition.3.combo.id.6': 'M',
  'GeneralSearch123.condition.3.combo.text.7': 'S',
  'GeneralSearch123.condition.3.combo.id.7': 'S',
  'GeneralSearch123.condition.3.combo.text.8': 'T',
  'GeneralSearch123.condition.3.combo.id.8': 'T',
  'GeneralSearch123.condition.3.combo.text.9': 'W',
  'GeneralSearch123.condition.3.combo.id.9': 'W',
  'GeneralSearch123.condition.3.combo.text.10': 'X',
  'GeneralSearch123.condition.3.combo.id.10': 'X',
  'GeneralSearch123.condition.3.combo.text.11': 'Y',
  'GeneralSearch123.condition.3.combo.id.11': 'Y',
  'GeneralSearch123.condition.3.combo.text.12': 'Z',
  'GeneralSearch123.condition.3.combo.id.12': 'Z',

  'GeneralSearch123.condition.4.labelValue': '小売形態',
  'GeneralSearch123.condition.4.fieldType': '3',
  'GeneralSearch123.condition.4.paramName': 'condition04',
  'GeneralSearch123.condition.4.fieldMaxLength': '2',
  'GeneralSearch123.condition.4.combo.text.1': 'AP',
  'GeneralSearch123.condition.4.combo.id.1': 'AP',
  'GeneralSearch123.condition.4.combo.text.2': 'CP',
  'GeneralSearch123.condition.4.combo.id.2': 'CP',
  'GeneralSearch123.condition.4.combo.text.3': 'CV',
  'GeneralSearch123.condition.4.combo.id.3': 'CV',
  'GeneralSearch123.condition.4.combo.text.4': 'DP',
  'GeneralSearch123.condition.4.combo.id.4': 'DP',
  'GeneralSearch123.condition.4.combo.text.5': 'DR',
  'GeneralSearch123.condition.4.combo.id.5': 'DR',
  'GeneralSearch123.condition.4.combo.text.6': 'DS',
  'GeneralSearch123.condition.4.combo.id.6': 'DS',
  'GeneralSearch123.condition.4.combo.text.7': 'GG',
  'GeneralSearch123.condition.4.combo.id.7': 'GG',
  'GeneralSearch123.condition.4.combo.text.8': 'HH',
  'GeneralSearch123.condition.4.combo.id.8': 'HH',
  'GeneralSearch123.condition.4.combo.text.9': 'JJ',
  'GeneralSearch123.condition.4.combo.id.9': 'JJ',
  'GeneralSearch123.condition.4.combo.text.10': 'NC',
  'GeneralSearch123.condition.4.combo.id.10': 'NC',
  'GeneralSearch123.condition.4.combo.text.11': 'NR',
  'GeneralSearch123.condition.4.combo.id.11': 'NR',
  'GeneralSearch123.condition.4.combo.text.12': 'RC',
  'GeneralSearch123.condition.4.combo.id.12': 'RC',
  'GeneralSearch123.condition.4.combo.text.13': 'RR',
  'GeneralSearch123.condition.4.combo.id.13': 'RR',
  'GeneralSearch123.condition.4.combo.text.14': 'SM',
  'GeneralSearch123.condition.4.combo.id.14': 'SM',
  'GeneralSearch123.condition.4.combo.text.15': 'SS',
  'GeneralSearch123.condition.4.combo.id.15': 'SS',
  'GeneralSearch123.condition.4.combo.text.16': 'TT',
  'GeneralSearch123.condition.4.combo.id.16': 'TT',
  'GeneralSearch123.condition.4.combo.text.17': 'WS',
  'GeneralSearch123.condition.4.combo.id.17': 'WS',
  'GeneralSearch123.condition.4.combo.text.18': 'XX',
  'GeneralSearch123.condition.4.combo.id.18': 'XX',
  'GeneralSearch123.condition.4.combo.text.19': 'ZZ',
  'GeneralSearch123.condition.4.combo.id.19': 'ZZ',

  // 検索結果表示部項目設定
  'GeneralSearch123.result.1.headerTitle': 'ﾁｬﾈﾙｺｰﾄﾞ',
  'GeneralSearch123.result.1.columnWidth': '70',
  'GeneralSearch123.result.1.resultName': 'result01',

  'GeneralSearch123.result.2.headerTitle': 'ﾁｬﾈﾙ名称',
  'GeneralSearch123.result.2.columnWidth': '230',
  'GeneralSearch123.result.2.resultName': 'result02',

  'GeneralSearch123.result.3.headerTitle': '取引形態',
  'GeneralSearch123.result.3.columnWidth': '70',
  'GeneralSearch123.result.3.resultName': 'result03',

  'GeneralSearch123.result.4.headerTitle': '小売形態',
  'GeneralSearch123.result.4.columnWidth': '85',
  'GeneralSearch123.result.4.resultName': 'result04',
}
