<template>
  <TextLabelValue
    :x="16"
    :y="16"
    :label="`工場`"
    :label-width="128"
    :text-value1="logic.cdKojoZaikoBasho"
    :text-value2="logic.nmKojoZaikoBasho"
    :no-koron="false"
  />
  <TextLabelValue
    :x="312"
    :y="16"
    :label="`入荷区分`"
    :label-width="112"
    :text-value1="logic.stNyuka"
    :text-value2="logic.nmNyuka"
    :no-koron="false"
  />
  <TextLabelValue
    :x="552"
    :y="16"
    :label="`データ区分`"
    :label-width="96"
    :text-value1="logic.stData"
    :text-value2="logic.nmData"
    :no-koron="false"
  />
  <TextLabelValue
    :x="728"
    :y="16"
    :label="`実績フラグ`"
    :label-width="112"
    :text-value1="logic.fgJisseki"
    :text-value2="logic.nmJisseki"
    :text-value3="logic.page"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="48"
    :label="`レコードSEQ№`"
    :label-width="128"
    :text-value1="logic.noRecSeq"
    :no-koron="false"
  />
  <TextLabelValue
    :x="312"
    :y="48"
    :label="`MES管理番号`"
    :label-width="112"
    :text-value1="logic.noMesKanri"
    :no-koron="false"
  />
  <TextLabelValue
    :x="552"
    :y="48"
    :label="`訂正区分`"
    :label-width="96"
    :text-value1="logic.stTeisei"
    :text-value2="logic.nmTeisei"
    :no-koron="false"
  />
  <TextLabelValue
    :x="744"
    :y="48"
    :label="`データ作成日時`"
    :label-width="136"
    :text-value1="logic.nmKojo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="80"
    :label="`展開状態`"
    :label-width="128"
    :text-value1="logic.nmTenkai"
    :no-koron="false"
  />
  <TextLabelValue
    :x="312"
    :y="80"
    :label="`状態`"
    :label-width="112"
    :text-value1="logic.ifJyoutai"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="112"
    :label="`受信キー\r\n`"
    :label-width="128"
    :text-value1="logic.cdJushinkey"
    :no-koron="false"
  />
  <TextLabelValue
    :x="312"
    :y="112"
    :label="`受信日時\r\n`"
    :label-width="112"
    :text-value1="logic.tmJushin"
    :no-koron="false"
  />
  <TextLabelValue
    :x="728"
    :y="112"
    :label="`分割データ№`"
    :label-width="112"
    :text-value1="logic.noBunkatsuData"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="160"
    :label="`品目`"
    :label-width="128"
    :text-value1="logic.nmItemCdShikibetsu"
    :text-value2="logic.cdItem"
    :text-value3="logic.nmHinmpkuRyakushiki"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="160"
    :label="`取引先（原材料）`"
    :label-width="144"
    :text-value1="logic.cdTorihikisaki2"
    :text-value2="logic.nmTorihikisaki2"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="192"
    :label="`取引先`"
    :label-width="128"
    :text-value1="logic.cdTorihikisaki"
    :text-value2="logic.nmTorihikisaki"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="192"
    :label="`生産工場`"
    :label-width="144"
    :text-value1="logic.cdSeisanKojo"
    :text-value2="logic.nmSeisanKojo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="224"
    :label="`出荷場所`"
    :label-width="128"
    :text-value1="logic.cdSyukasoko"
    :text-value2="logic.nmSyukasoko"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="224"
    :label="`入荷場所`"
    :label-width="144"
    :text-value1="logic.cdNyukasoko"
    :text-value2="logic.nmNyukasoko"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="256"
    :label="`数量`"
    :label-width="128"
    :text-value1="logic.qtSuryo"
    :text-value2="logic.ifSuryotani"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="256"
    :label="`重量`"
    :label-width="144"
    :text-value1="logic.qtJuryo"
    :text-value2="logic.ifJuryotani"
    :no-koron="false"
  />
  <TextLabelValue
    :x="808"
    :y="256"
    :label="`入荷予定日`"
    :label-width="112"
    :text-value1="logic.dtUkeireyotei"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="288"
    :label="`賞味期限`"
    :label-width="128"
    :text-value1="logic.dtShomikigen"
    :no-koron="false"
  />
  <TextLabelValue
    :x="240"
    :y="288"
    :label="`等級`"
    :label-width="112"
    :text-value1="logic.ifTokyu"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="288"
    :label="`ロット`"
    :label-width="144"
    :text-value1="logic.ifLot"
    :no-koron="false"
  />
  <TextLabelValue
    :x="808"
    :y="288"
    :label="`サブロット`"
    :label-width="112"
    :text-value1="logic.ifSublot"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="320"
    :label="`払出伝票年月日`"
    :label-width="128"
    :text-value1="logic.dtHaraidashiDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="240"
    :y="320"
    :label="`払出伝票番号`"
    :label-width="112"
    :text-value1="logic.noHaraidashiDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="320"
    :label="`被訂正伝票年月日`"
    :label-width="144"
    :text-value1="logic.dtHiteiseiDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="784"
    :y="320"
    :label="`被訂正伝票番号`"
    :label-width="136"
    :text-value1="logic.noHteiseiDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="360"
    :label="`出荷伝票番号`"
    :label-width="128"
    :text-value1="logic.noSyukaDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="360"
    :label="`入荷伝票番号`"
    :label-width="144"
    :text-value1="logic.noNyukaDenpyo"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="424"
    :label="`出荷場所`"
    :label-width="128"
    :text-value1="logic.cdSyukaSokoHikiate"
    :text-value2="logic.nmSyukaSokoHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="424"
    :label="`数量`"
    :label-width="144"
    :text-value1="logic.qtSuryoHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="808"
    :y="424"
    :label="`重量`"
    :label-width="112"
    :text-value1="logic.qtJuryoHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="456"
    :label="`賞味期限`"
    :label-width="128"
    :text-value1="logic.dtshomikigenHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="240"
    :y="456"
    :label="`等級`"
    :label-width="112"
    :text-value1="logic.ifTokyuHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="456"
    :label="`ロット`"
    :label-width="144"
    :text-value1="logic.ifLotHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="808"
    :y="456"
    :label="`サブロット`"
    :label-width="112"
    :text-value1="logic.ifSublotHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="16"
    :y="488"
    :label="`取引先`"
    :label-width="128"
    :text-value1="logic.cdTorihikisakiHikiate"
    :text-value2="logic.nmTorihikisakiHikiate"
    :no-koron="false"
  />
  <TextLabelValue
    :x="504"
    :y="488"
    :label="`生産工場`"
    :label-width="144"
    :text-value1="logic.cdSeisanKojoHikiate"
    :text-value2="logic.nmSeisanKojoHikiate"
    :no-koron="false"
  />
  <BaseText
    :x="16"
    :y="392"
    :Font-Size="14"
    :height="24"
    :width="112"
    :label="`引当変更後情報`"
  />
  <BaseDivider :x="8" :y="144" />
  <BaseDivider :x="8" :y="352" />
</template>

<script lang="ts" setup>
// 共通部品を導入する。
import TextLabelValue from '@/components/atoms/TextLabelValue.vue'
import BaseText from '@/components/atoms/BaseText.vue'
import BaseDivider from '@/components/atoms/BaseDivider.vue'

// ロジックを導入する。
import useYPMGSSF701SLogic from './YPMGSSF701S-logic'

// ロジックのインスタンス取得。リアクティビティを保つため、reactiveを使用する。
import { reactive } from 'vue'
const logic = reactive(useYPMGSSF701SLogic())
</script>
